[build]
  publish = "."
  command = "./build-clean.sh"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Explicitly disable all auto-detection
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200