[build]
  publish = "."
  command = "./build.sh"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Disable all auto-detected plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    disable = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
